apiVersion: v1
kind: Service
metadata:
    name: madome-library
spec:
    type: NodePort
    selector:
        app: madome-library
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32764
